-- CreateEnum
CREATE TYPE "public"."AlertType" AS ENUM ('CYCLONE', 'STORM_SURGE', 'COASTAL_EROSION', 'WATER_POLLUTION');

-- CreateEnum
CREATE TYPE "public"."AlertSeverity" AS ENUM ('LOW', 'MODERATE', 'HIGH', 'EXTREME');

-- CreateEnum
CREATE TYPE "public"."AlertStatus" AS ENUM ('GENERATED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SENT');

-- CreateTable
CREATE TABLE "public"."Alert" (
    "id" SERIAL NOT NULL,
    "type" "public"."AlertType" NOT NULL,
    "severity" "public"."AlertSeverity" NOT NULL,
    "status" "public"."AlertStatus" NOT NULL DEFAULT 'GENERATED',
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "coordinates" JSONB,
    "predictionData" JSONB NOT NULL,
    "mlPrediction" DOUBLE PRECISION NOT NULL,
    "thresholdMet" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "approvedAt" TIMESTAMP(3),
    "sentAt" TIMESTAMP(3),
    "reviewedById" INTEGER,
    "reviewNotes" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "Alert_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Alert_status_createdAt_idx" ON "public"."Alert"("status", "createdAt");

-- CreateIndex
CREATE INDEX "Alert_state_status_idx" ON "public"."Alert"("state", "status");

-- CreateIndex
CREATE INDEX "Alert_type_severity_idx" ON "public"."Alert"("type", "severity");

-- AddForeignKey
ALTER TABLE "public"."Alert" ADD CONSTRAINT "Alert_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
